accounts/urls.py
from django.urls import path
from .views import *
from django.urls import reverse

app_name = 'accounts'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),


]

icetin/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('post/',include('post.urls')),
    path('accounts/',include('accounts.urls')),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *
from django.urls import reverse

app_name = 'post'
urlpatterns = [
    path('index/', post_index, name='index'),
    path('create/', post_create, name='create'),
    path('<slug>/', post_detail, name='detail'),
    path('<slug>/update/', post_update, name='update'),
    path('<slug>/delete/', post_delete, name='delete'),

]

accounts/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from ckeditor.fields import RichTextField

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey('auth.User',verbose_name='Yazar',on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(verbose_name='Yazı Başlığı', max_length=250)
    content = RichTextField(verbose_name='Yazı İçeriği')
    publishing_date = models.DateTimeField(verbose_name='Yayımlanma Tarihi',auto_now_add=True)
    image = models.ImageField(null=True, blank=True)
    slug = models.SlugField(unique=True, editable=False, max_length=300)


    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('post:detail', kwargs={'slug':self.slug})
        # return "/post/{}".format(self.id)

    def get_create_url(self):
        return reverse('post:create')

    def get_update_url(self):
        return reverse('post:update', kwargs={'slug':self.slug})

    def get_delete_url(self):
        return reverse('post:delete', kwargs={'slug':self.slug})

    def get_unique_slug(self):
        slug = slugify(self.title.replace('ı','i'))
        unique_slug = slug
        counter = 1
        while Post.objects.filter(slug=unique_slug):
            unique_slug ='{}-{}'.format(slug, counter)
            counter += 1
        return unique_slug


    def save(self,*args,**kwargs):
        self.slug = self.get_unique_slug()
        return super(Post, self).save(*args,**kwargs)


    class Meta:
        ordering = ['-publishing_date','id']


class Comment(models.Model):
    post = models.ForeignKey('post.Post',related_name='comments', on_delete=models.CASCADE)

    name = models.CharField(max_length=200, verbose_name='İsim')
    content = models.TextField(verbose_name='Yorum')
    created_date = models.DateTimeField(auto_now_add=True)

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, label='Kullanıcı Adı')
    password = forms.CharField(max_length=100, label='Parola', widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('Kullanıcı adını veya parolayı yanlış girdiniz!')
            return super(LoginForm, self).clean()


class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=100, label='Kullanıcı Adı')
    firstname = forms.CharField(max_length=100, label='Gerçek Adı')
    lastname = forms.CharField(max_length=100, label='Gerçek Soyadı')
    password1 = forms.CharField(max_length=100, label='Parola', widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=100, label='Parola Doğrulama', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'firstname',
            'lastname',
            'password1',
            'password2',
        ]

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Parolalar eşleşmiyor!")
        return password2

post/forms.py
from django import forms
from .models import Post, Comment
from captcha.fields import ReCaptchaField


class PostForm(forms.ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',

        ]

class CommentForm(forms.ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Comment
        fields = [
            'name',
            'content',
        ]

home/views.py
from django.shortcuts import render

import sys
import os

from post.models import Post

# Create your views here.



def home_view(request):
    posts_list = Post.objects.all()
    print(len(posts_list))
    if request.user.is_authenticated:

        context = {
            'isim':request.user.get_full_name,
        }
    else:
        context = {
            'isim': 'Misafir',
        }
    return render(request, 'home.html',{"context":context,"posts":posts_list})

templates/accounts/form.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <h1>{{ title }}</h1>
                            {{ form|crispy }}
                            <input class="btn btn-primary" type="submit" value="{{ title }}">
                        </form>
                </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8", name="viewport" content="width=device-width, inital-scale=1">
    <title>{% block title %}icetin Sitesi{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

</head>
<body>
    {% include 'header.html' %}

    {% include 'messages.html' %}

    {% block body %}

    {% endblock %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href="{% url 'home' %}">Yemek Tarifleri</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



  <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <form class="form-inline my-2 my-lg-0" method="get">
      <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" value="{{ request.GET.q }}" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" value="Ara" type="submit">Search</button>
    </form>


    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link " href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'post:index' %}">Post</a>
      </li>

    {% if not request.user.is_authenticated %}


    <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:register' %}">Üye Ol</a>
      </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">Giriş</a>
      </li>
                  <li class="nav-item">
            <a class="nav-link" href="">{{ isim }}</a>
          </li>
    {% else %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">Çıkış</a>
      </li>

    {% endif %}

        {% if request.user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'post:create' %}">Yazı ekle</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">{{ isim }}</a>
          </li>

        {% endif %}

{#      <li class="nav-item dropdown">#}
{#        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#          Dropdown#}
{#        </a>#}
{#        <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#          <a class="dropdown-item" href="#">Action</a>#}
{#          <a class="dropdown-item" href="#">Another action</a>#}
{#          <div class="dropdown-divider"></div>#}
{#          <a class="dropdown-item" href="#">Something else here</a>#}
{#        </div>#}
{#      </li>#}
{#      <li class="nav-item">#}
{#        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>#}
{#      </li>#}
    </ul>


  </div>
</nav>

templates/messages.html
{% if messages %}

    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>{{ message }}!</strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

    {% endfor %}

{% endif %}

templates/post/comment.html
{% load crispy_forms_tags %}

<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="Yorum Ekle">
</form>

templates/post/detail.html
{% extends 'base.html'%}

{% block body %}


    <div class="container">

        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card" >
                  <div class="card-body">
                      {% if post.image %}
                          <img src="{{ post.image.url }}" class="img-fluid" alt="Post Img">
                      {% endif %}
                    <h5 class="card-title">{{ post.title }} <small>{{ post.publishing_date }}</small></h5>
                    <h6> Yazar: {{ post.user.get_full_name }}</h6>
                    <p class="card-text">{{ post.content | safe | linebreaks }}</p>
                    <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Git</a>
                        {% if request.user.is_authenticated %}
                            <a href="{{ post.get_delete_url }}" class="btn btn-danger">Sil</a>
                            <a href="{{ post.get_update_url }}" class="btn btn-info">Güncelle</a>
                        {% endif %}
                  </div>
                </div>

            <br><br><hr>
            <h3>Yorum Ekle:</h3>
            {% include 'post/comment.html' %}
            <hr>

            {% for comment in post.comments.all %}
                <h4>{{ comment.name }} | <small>{{ comment.created_date|timesince }} önce</small></h4>
                <p>{{ comment.content | linebreaks }}</p>
            {% endfor %}


            </div>
        </div>

    </div>

{% endblock %}

templates/post/form.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <h1>Form</h1>
                            {{ form|crispy }}
                            {{ form.media }}
                            <input class="btn btn-primary" type="submit" value="Gönder">
                        </form>
                </div>
        </div>
    </div>
{% endblock %}

templates/post/index.html
{% extends 'base.html'%}

{% block body %}
{#post/{{ post.id }}#}
{#{% url 'detail' id=post.id %}#}
    <div class="container">
    {% for post in posts %}
        <div class="row">
            <div class="col-md-8 offset-md-3">
                <div class="card" >
                  <div class="card-body">
                      {% if post.image %}
                          <img src="{{ post.image.url }}" class="img-fluid">
                      {% endif %}
                    <h5 class="card-title">{{ post.title }} <small>{{ post.publishing_date | timesince }} önce</small></h5>
                    <h6 style="text-transform: capitalize;"> Yazar: {{ post.user.get_full_name }}</h6>
                    <p class="card-text">{{ post.content | safe | linebreaks | truncatewords:15}}</p>
                    <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Git</a>
                        {% if request.user.is_authenticated %}
                            <a href="{{ post.get_delete_url }}" class="btn btn-danger">Sil</a>
                            <a href="{{ post.get_update_url }}" class="btn btn-info">Güncelle</a>
                        {% endif %}
                  </div>
                </div>
            </div>
        </div>
    {% endfor %}

        <div class="row">
            <div class="col-md-8 offset-md-3">
                <div class="pagination">
                    <span class="step-links">
                        {% if posts.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ posts.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                        </span>

                        {% if posts.has_next %}
                            <a href="?page={{ posts.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
                            <a href="?page={{ posts.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>






    </div>


{% endblock %}